services:
  # PostGIS Database
  postgis:
    image: postgis/postgis:15-3.3
    container_name: geoint-postgis
    environment:
      POSTGRES_DB: POI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r00t01
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - geoint-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d POI"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # .NET WebAPI with built-in migration
  webapi:
    build:
      context: .
      dockerfile: GeoInt.WebApi/Dockerfile
    container_name: geoint-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostGisConnection=Host=postgis;Database=POI;Username=postgres;Password=r00t01;
      - FeatureToggles__UsePostGis=true
      - FeatureToggles__UseSqlServer=false
      - FeatureToggles__UseMongoDb=false
    ports:
      - "5000:8080"
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - geoint-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/pois || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React Frontend (Future - commented out)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: geoint-frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - webapi
  #   networks:
  #     - geoint-network
  #   environment:
  #     - REACT_APP_API_URL=http://webapi:8080

volumes:
  postgis_data:
    driver: local

networks:
  geoint-network:
    driver: bridge 