services:
  # PostGIS Database
  postgis:
    image: postgis/postgis:15-3.3
    pull_policy: always
    container_name: geoint-postgis
    environment:
      POSTGRES_DB: POI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r00t01
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - geoint-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d POI"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Database Migration Service
  db-migration:
    build:
      context: .
      dockerfile: GeoInt.WebApi/Dockerfile
      target: build
      pull: true
    container_name: geoint-migration
    environment:
      - ConnectionStrings__PostGisConnection=Host=postgis;Database=POI;Username=postgres;Password=r00t01;
      - FeatureToggles__UsePostGis=true
      - FeatureToggles__UseSqlServer=false
      - FeatureToggles__UseMongoDb=false
    working_dir: /src
    command: >
      sh -c "
        echo 'Installing EF Core tools...' &&
        dotnet tool install --global dotnet-ef &&
        echo 'Waiting for database to be ready...' &&
        sleep 15 &&
        echo 'Running database migrations...' &&
        /root/.dotnet/tools/dotnet-ef database update --project GeoInt.Persistance.PostGis --startup-project GeoInt.WebApi --configuration Release &&
        echo 'Database migration completed successfully!'
      "
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - geoint-network
    restart: "no"

  # .NET WebAPI
  webapi:
    build:
      context: .
      dockerfile: GeoInt.WebApi/Dockerfile
      pull: true
    container_name: geoint-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostGisConnection=Host=postgis;Database=POI;Username=postgres;Password=r00t01;
      - FeatureToggles__UsePostGis=true
      - FeatureToggles__UseSqlServer=false
      - FeatureToggles__UseMongoDb=false
    ports:
      - "5000:8080"
    depends_on:
      postgis:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
    networks:
      - geoint-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/pois || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vue.js Frontend
  frontend:
    build:
      context: ./GeoInt.Web.UI
      dockerfile: Dockerfile
      pull: false
    container_name: geoint-frontend
    ports:
      - "5001:80"
    depends_on:
      webapi:
        condition: service_healthy
    networks:
      - geoint-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgis_data:
    driver: local

networks:
  geoint-network:
    driver: bridge 